# Generated by Django 2.1.3 on 2018-11-27 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_tags_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='thumbnail_url',
            field=models.TextField(blank=True, default='', validators=[django.core.validators.URLValidator()]),
        ),
    ]
